services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - _data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  _data: